### ISSUE TITLE
`not in whitelist` error during develop

### ISSUE THREAD

**Issue by brucx** [OpenProduct/openmask-extension#16]
**Describe the bug**

When I call `provider.send('ton_requestAccounts')` in my under developing project, I meet an error like:

```
{
    "message": "Origin \"http://localhost:3000\" is not in whitelist",
    "code": 1001
}
```

**Expected behavior**

disable whitelist in testnet env

**Screenshots**
![image](https://user-images.githubusercontent.com/1300652/229125568-d4d4b259-1d20-48df-a864-d18f11ed40b9.png)

**Comment by brucx** [comment]
@KuznetsovNikita Would you mind helping me with this?

**Comment by KuznetsovNikita** [comment]
> @KuznetsovNikita Would you mind helping me with this?

Good day, 
I mentioned the same issue, some time ago.
Is it happen on latest version?

In general it may happen because, openmask save cache for this origin and can’t find relation, because for example connected wallet was removed.

I will check this place one more time.

In case you would like to quickly fix your openmask, just reinstall it.

Thank you for the report
Nikita

**Comment by KuznetsovNikita** [comment]
I rework connection flow:
https://github.com/OpenProduct/openmask-extension/compare/v0.18.4...v0.18.5

**Comment by KuznetsovNikita** [comment]
The fix deployed and released
